import { useEffect, useMemo, useState } from 'react';
import { api, setToken, getToken } from './lib/api';
import { connectSocket } from './lib/socket';

type User = { id:string; name:string; email:string; role:'ADMIN'|'PM'|'DEVELOPER' };
type Task = { id:number; title:string; status:string; priority:string; dueDate:string; project:{id:string;name:string}; developer:{name:string} };
type Activity = { id:number; message:string; createdAt:string; user:{name:string} };

export function App(){
 const [user,setUser]=useState<User|null>(null); const [login,setLogin]=useState({email:'admin@demo.com',password:'Password123!'}); const [error,setError]=useState(''); const [tasks,setTasks]=useState<Task[]>([]); const [activities,setActivities]=useState<Activity[]>([]); const [notifications,setNotifications]=useState<any[]>([]); const [unread,setUnread]=useState(0); const [online,setOnline]=useState(0); const [status,setStatus]=useState(''); const [priority,setPriority]=useState('');
 const load=async(u:User)=>{ const params=new URLSearchParams(); if(status)params.set('status',status);if(priority)params.set('priority',priority); const [t,a,n,d]=await Promise.all([api(`/api/tasks?${params}`), api('/api/activity'), api('/api/notifications'),api('/api/dashboard')]); if(t.ok)setTasks((await t.json()).tasks); if(a.ok)setActivities((await a.json()).activities||[]); if(n.ok){const x=await n.json();setNotifications(x.notifications);setUnread(x.unread)} if(d.ok)setOnline((await d.json()).onlineUsers); };
 useEffect(()=>{ (async()=>{const r=await api('/api/auth/refresh',{method:'POST'});if(r.ok){const d=await r.json();setToken(d.accessToken);setUser(d.user)}})();},[]);
 useEffect(()=>{if(!user)return; load(user); const s=connectSocket(getToken()); s.on('presence:update',setOnline); s.on('notification:new',()=>load(user)); s.on('activity:new',(a)=>setActivities(x=>[a,...x].slice(0,20))); return()=>{s.disconnect()};},[user,status,priority]);
 const projectIds=useMemo(()=>Array.from(new Set(tasks.map(t=>t.project.id))),[tasks]);

 async function doLogin(e:any){e.preventDefault();setError('');const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify(login)});const d=await r.json();if(!r.ok)return setError(d.error?.message||'Login failed');setToken(d.accessToken);setUser(d.user)}
 if(!user)return <main className="login"><form onSubmit={doLogin}><h1>Project Dashboard</h1><p>Velozity technical assessment</p><input value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button>Sign in</button>{error&&<small>{error}</small>}<div className="demo">Admin: admin@demo.com<br/>PM: ravi@demo.com<br/>Developer: aman@demo.com<br/>Password: Password123!</div></form></main>;
 async function changeStatus(id:number,next:string){const r=await api(`/api/tasks/${id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});if(r.ok)load(user);else alert((await r.json()).error?.message||'Update failed')}
 async function logout(){await api('/api/auth/logout',{method:'POST'});setToken('');setUser(null)}
 return <main><header><div><h1>Client Project Dashboard</h1><span>{user.name} · {user.role}</span></div><div className="header-actions"><span>Online: {online}</span><span className="bell">🔔 {unread}</span><button onClick={logout}>Logout</button></div></header><section className="summary"><div><b>{tasks.length}</b><span>Visible tasks</span></div><div><b>{tasks.filter(t=>t.status==='OVERDUE').length}</b><span>Overdue</span></div><div><b>{projectIds.length}</b><span>Projects</span></div></section><section className="filters"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All status</option><option>TODO</option><option>IN_PROGRESS</option><option>IN_REVIEW</option><option>DONE</option><option>OVERDUE</option></select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priority</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></section><div className="grid"><section><h2>{user.role==='DEVELOPER'?'My Tasks':'Tasks'}</h2>{tasks.map(t=><article className="task" key={t.id}><div><b>#{t.id} {t.title}</b><p>{t.project.name} · {t.priority} · due {new Date(t.dueDate).toLocaleDateString()}</p></div>{user.role!=='ADMIN' || true?<select value={t.status} onChange={e=>changeStatus(t.id,e.target.value)} disabled={user.role==='DEVELOPER'&&false}><option>TODO</option><option>IN_PROGRESS</option><option>IN_REVIEW</option><option>DONE</option><option>OVERDUE</option></select>:null}</article>)}</section><aside><h2>Live Activity</h2>{activities.map(a=><div className="activity" key={a.id}><b>{a.user?.name}</b> {a.message.replace(a.user?.name||'','')}<small>{new Date(a.createdAt).toLocaleString()}</small></div>)}<h2>Notifications</h2>{notifications.slice(0,5).map(n=><div className="notification" key={n.id}>{n.message}</div>)}</aside></div></main>;
}
